name: rocket_guide
description: An easy to use index of all SpaceX rockets.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.6
  flutter_riverpod: ^0.13.0-nullsafety.3
  freezed_annotation: ^0.13.0-nullsafety.0
  google_fonts: ^2.0.0-nullsafety.0
  http: ^0.13.0
  json_annotation: ^4.0.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  freezed: ^0.12.7
  json_serializable: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
